<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCx44x8j\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCx44x8j/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCx44x8j.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCx44x8j\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerCx44x8j\App_KernelProdContainer([
    'container.build_hash' => 'Cx44x8j',
    'container.build_id' => '66dd1cb6',
    'container.build_time' => 1773085748,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCx44x8j');
